name: 02-basic-example
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v7
      - name: Install NodeJS
        uses: actions/setup-node@v7
        with: 
          node-version: "24"
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Test the code
        run: npm test
      - name: Build Project
        run: npm run build