name: Issues
on: workflow_dispatch
jobs:
    outputinfo:
        runs-on: ubuntu_latest
        steps:
          - name: getting the issues outputinfo from github
            run: echo "${{ toJSON(github)}}"
           

