name: Issues
on: issues
jobs:
    outputinfo:
        runs-on: ubuntu-latest
        steps:
          - name: getting the issues outputinfo from github
            run: echo "${{ toJSON(github.event)}}"
           

